### ISSUE TITLE
Failed to obtain a distributed lock for actor system after 0 retries. 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#10]
> 22.01.2018 12:34:39.754 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,   28] - Failed to obtain a distributed lock for actor system [test] after 0 retries. Closing. Consul.ConsulRequestException: Unexpected response, status code BadRequest: Invalid service address
   at Consul.PutRequest`1.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<RegisterNodeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<TryJoinAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<>c__DisplayClass14_0.<<-ctor>b__0>d.MoveNext()

The full HOCON

```hocon
akka {
    log-config-on-start = off
    stdout-loglevel = DEBUG
    loglevel = INFO
    loggers = ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
    actor {
      provider = cluster
      debug {
          receive = on
          autoreceive = on
          lifecycle = on
          event-stream = on
          unhandled = on
      }
    }
  remote {
    dot-netty.tcp {
    }
    log-remote-lifecycle-events = INFO
  }
  cluster {
    discovery {
      provider = akka.cluster.discovery.consul
      consul {
        listener-url = "http://127.0.0.1:8500"
        class = "Akka.Cluster.Discovery.Consul.ConsulDiscoveryService, Akka.Cluster.Discovery.Consul"
        alive-interval = 10s
        alive-timeout = 1m
        refresh-interval = 1m
        join-retries = 3
        lock-retry-interval = 250ms
        datacenter = ""
        token = ""
        wait-time = 30s
      }
    }               
  }
```
Consul config:
```json
{
  "datacenter": "dc",
  "bind_addr": "10.65.xx.xx",
  "data_dir": "c:/consul/data",
  "log_level": "INFO",
  "server": true,
  "leave_on_terminate": false,
  "skip_leave_on_interrupt": true,
  "rejoin_after_leave": true,
  "ui": true,
  "client_addr": "0.0.0.0",
  "bootstrap_expect": 3,
  "retry_join": [ 
    "10.65.xx.xx:8301",
    "10.65.xx.xx:8301",
    "10.70.xx.xx:8301"
  ]
}
```
Consul cluster contains 3 nodes, all of them are servers. The status in its web UI is OK, the only service I can see is "consul".

**Comment by Horusiath** [comment]
How many services are you trying to connect at once?

One thing for sure is bug with amount of retries written :) Consul service discovery tries to acquire a distributed lock from consul in order to guarantee, that only single node at the time will initialize the cluster (if there were two of them trying to initialize it at the same time, we'd end up with 2 separate clusters).

My assumption is that a distributed lock is not released i.e. because node died before releasing it, and a lock acquisition timeout is too long. Example scenario:

1. Node A acquires the distributed lock (there's no timeout provided, so we're using consul's defaults here, let's say it's 10 sec).
2. Node A dies before releasing the lock.
3. Node B tries to acquire the lock for the first of `join-retries` (3) attempts - it failed, since lock was not released by A yet.
4. Node B waits for `lock-retry-interval` (250ms) and tries to acquire lock  again... and again. 
5. Ultimately node B gives up, since it didn't manage to acquire lock for consecutive number of times. That's because the Consul lock acquisition timeout in consul was longer than `join-retries` * `lock-retry-interval`.

What is necessary here is to check, for how long Consul allows distributed lock to be held, and either:

1. Change that on Consul configuration level.
2. Adjust that setting to `lock-retry-interval` so that retry actually will have sense.
3. Ideally, check if this can be configured from consul client level and add one more extra setting in this library.

**Comment by vasily-kirichenko** [comment]
There is single node in "klsrl" akka cluster :) after that error a key is left in consul:

![image](https://user-images.githubusercontent.com/873919/35217353-fb510b70-ff7b-11e7-9d1f-81a781b9febf.png)

I set `lock-retry-interval` to 5 seconds, same result - the error appeared instantly.

**Comment by Horusiath** [comment]
Did you got any log warnings? There should be something like *Failed to obtain a distributed lock for actor system*.

Also from what I see in Consul .NET client, the default session TTL is 15 seconds: https://github.com/PlayFab/consuldotnet/blob/fa7a1d2eebfe6482acd916dbac416881a9c6e0a8/Consul/Lock.cs#L554

Maybe try higher retry interval?

**Comment by vasily-kirichenko** [comment]
Yes, as before:
```
22.01.2018 13:57:57.431 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,    9] - Failed to obtain a distributed lock for actor system [klsrl] after 0 retries. Closing. Consul.ConsulRequestException: Unexpected response, status code BadRequest: Invalid service address
   at Consul.PutRequest`1.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<RegisterNodeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<TryJoinAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<>c__DisplayClass14_0.<<-ctor>b__0>d.MoveNext()
```

**Comment by vasily-kirichenko** [comment]
No warnings.

**Comment by Horusiath** [comment]
I'll add some more thorough log errors today and publish updated NuGet package. Btw. you've tried to use consul earlier with success, what has changed, that now you're getting those errors?

**Comment by vasily-kirichenko** [comment]
I've caught it! :)
```
remote {
    dot-netty.tcp {
        hostname = "127.0.0.1"  // it was not presented earlier and was defaulted to 0.0.0.0
    }
}
```
BTW, will 127.0.0.1 is a good value for a real cluster?

**Comment by Horusiath** [comment]
Hostname doesn't have to be IP, but if it is, it should be publicly recognized and accessible by other services/nodes. There is also a [public-hostname](https://github.com/akkadotnet/akka.net/issues/1186#issuecomment-125329757) setting, which you may want to be aware of in case of some issues.

**Comment by vasily-kirichenko** [comment]
I see. To be clear, must I set `hostname` to a real DNS name or a real IP in production? So I have to patch config files during deploy? Is there a magic value like `hostname = auto`?

**Comment by Horusiath** [comment]
Hostname can be DNS or IP (in case of DNS, it will be resolved for socket purposes) - the only thing here is that host:port will be used inside particular node `Address` - the address comparison is lexical, so *akka.tcp://system@127.0.0.1:5000/* will not be the same as *akka.tcp://system@localhost:5000/*. No matter which one will you use (DNS or IP), remember to keep it consistent between nodes in your cluster.
