### ISSUE TITLE
Second node cannot join the seed node

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#14]
```
23.01.2018 17:03:29.966 WARN  [Akka.Cluster.JoinSeedNodeProcess,   94] - Couldn't join seed nodes after [3] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:30.137 WARN  [Akka.Remote.EndpointWriter,  259] - AssociationError [akka.tcp://klsrl@0.0.0.0:2552] -> akka.tcp://klsrl@other-node:2552: Error [Association failed with akka.tcp://klsrl@other-node:2552] [] 
23.01.2018 17:03:30.306 WARN  [Akka.Event.DummyClassForStringSources,  290] - Tried to associate with unreachable remote address [akka.tcp://klsrl@other-node:2552]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://klsrl@other-node:2552] Caused by: [System.AggregateException: One or more errors occurred. ---> Akka.Remote.Transport.InvalidAssociationException: connection timed out: 10.65.61.3:2552
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__11_54(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) Akka.Remote.Transport.InvalidAssociationException: connection timed out: 10.65.61.3:2552
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()<---
] 
23.01.2018 17:03:30.387 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-1 to akka://klsrl/deadLetters was not delivered. 1 dead letters encountered. 
23.01.2018 17:03:30.387 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-2 to akka://klsrl/deadLetters was not delivered. 2 dead letters encountered. 
23.01.2018 17:03:30.387 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-3 to akka://klsrl/deadLetters was not delivered. 3 dead letters encountered. 
23.01.2018 17:03:30.387 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-3 to akka://klsrl/deadLetters was not delivered. 4 dead letters encountered. 
23.01.2018 17:03:30.398 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-3 to akka://klsrl/deadLetters was not delivered. 5 dead letters encountered. 
23.01.2018 17:03:30.398 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  222] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-3 to akka://klsrl/deadLetters was not delivered. 6 dead letters encountered. 
23.01.2018 17:03:30.398 INFO  [Akka.Actor.LocalActorRef,  222] - Message AckIdleCheckTimer from akka://klsrl/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fklsrl%40other-node%3A2552-1/endpointWriter to akka://klsrl/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fklsrl%40other-node%3A2552-1/endpointWriter was not delivered. 7 dead letters encountered. 
23.01.2018 17:03:30.398 INFO  [Akka.Actor.LocalActorRef,  222] - Message AckIdleCheckTimer from akka://klsrl/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fklsrl%40other-node%3A2552-1/endpointWriter to akka://klsrl/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2Fklsrl%40other-node%3A2552-1/endpointWriter was not delivered. 8 dead letters encountered. 
23.01.2018 17:03:34.979 WARN  [Akka.Cluster.JoinSeedNodeProcess,  193] - Couldn't join seed nodes after [4] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:34.979 INFO  [Akka.Remote.RemoteActorRefProvider+RemoteDeadLetterActorRef,  193] - Message InitJoin from akka://klsrl/system/cluster/core/daemon/joinSeedNodeProcess-3 to akka://klsrl/deadLetters was not delivered. 9 dead letters encountered. 
23.01.2018 17:03:40.001 WARN  [Akka.Cluster.JoinSeedNodeProcess,   95] - Couldn't join seed nodes after [5] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:44.994 WARN  [Akka.Cluster.JoinSeedNodeProcess,  135] - Couldn't join seed nodes after [6] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:50.015 WARN  [Akka.Cluster.JoinSeedNodeProcess,  115] - Couldn't join seed nodes after [7] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:55.018 WARN  [Akka.Cluster.JoinSeedNodeProcess,  191] - Couldn't join seed nodes after [8] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
23.01.2018 17:03:55.235 WARN  [Akka.Remote.EndpointWriter,  273] - AssociationError [akka.tcp://klsrl@0.0.0.0:2552] -> akka.tcp://klsrl@other-node:2552: Error [Association failed with akka.tcp://klsrl@other-node:2552] [] 
23.01.2018 17:03:55.235 WARN  [Akka.Event.DummyClassForStringSources,  273] - Tried to associate with unreachable remote address [akka.tcp://klsrl@other-node:2552]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://klsrl@other-node:2552] Caused by: [System.AggregateException: One or more errors occurred. ---> Akka.Remote.Transport.InvalidAssociationException: connection timed out: 10.65.61.3:2552
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Akka.Remote.Transport.ProtocolStateActor.<>c.<InitializeFSM>b__11_54(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) Akka.Remote.Transport.InvalidAssociationException: connection timed out: 10.65.61.3:2552
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Remote.Transport.DotNetty.DotNettyTransport.<Associate>d__22.MoveNext()<---
] 
23.01.2018 17:04:00.043 WARN  [Akka.Cluster.JoinSeedNodeProcess,  144] - Couldn't join seed nodes after [9] attempts, will try again. seed-nodes=[akka.tcp://klsrl@other-node:2552] 
```

**Comment by vasily-kirichenko** [comment]
Consul UI shows that the seed node is up and the service is up too.

**Comment by vasily-kirichenko** [comment]
Solved it: one of the servers has two network interfaces, changing hostname from host name to the proper IP has solved the issue.
