### ISSUE TITLE
Consul connectivity exception causes node to leaves cluster until restart

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#20]
```
03.02.2018 02:51:28.308 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,  944] - Couldn't retrieve collection of nodes from external service. Is current node unreachable? Shutting down... Consul.ConsulRequestException: Unexpected response, status code InternalServerError: rpc error making call: EOF
   at Consul.GetRequest`1.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<GetNodesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<ReconcileClusterStateAsync>d__19.MoveNext()
```

**Comment by vasily-kirichenko** [comment]
https://github.com/PlayFab/consuldotnet/issues/110

**Comment by vasily-kirichenko** [comment]
@Horusiath As you've fixed this bug, would you please publish a new NuGet package?

**Comment by Horusiath** [comment]
The new version v0.2.1 is now on NuGet: https://www.nuget.org/packages/Akka.Cluster.Discovery.Consul/0.2.1
