### ISSUE TITLE
Failed to obtain a distributed lock for actor system

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#24]
v. 0.2.1, Akka 1.3.6
```
25.04.2018 14:14:38.919 INFO  [Akka.Event.DummyClassForStringSources,    9] - Starting remoting 
25.04.2018 14:14:39.598 INFO  [Akka.Event.DummyClassForStringSources,   20] - Remoting started; listening on addresses : [akka.tcp://klsrl@10.70.16.67:2555] 
25.04.2018 14:14:39.614 INFO  [Akka.Event.DummyClassForStringSources,   20] - Remoting now listens on addresses: [akka.tcp://klsrl@10.70.16.67:2555] 
25.04.2018 14:14:39.704 INFO  [Akka.Event.DummyClassForStringSources,    5] - Cluster Node [akka.tcp://klsrl@10.70.16.67:2555] - Starting up... 
25.04.2018 14:14:39.789 INFO  [Akka.Event.DummyClassForStringSources,    4] - Cluster Node [akka.tcp://klsrl@10.70.16.67:2555] - Started up successfully 
25.04.2018 14:14:39.889 INFO  [Akka.Cluster.ClusterCoreDaemon,   26] - No seed-nodes configured, manual cluster join required 
25.04.2018 14:14:41.256 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,    7] - Failed to obtain a distributed lock for actor system [klsrl]. Remaining retries: [2] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<>c__DisplayClass12_0.<GetNodesAsync>b__0(ServiceEntry x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Akka.Cluster.Discovery.DiscoveryService.<TryJoinAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<>c__DisplayClass16_1.<<-ctor>b__1>d.MoveNext()
25.04.2018 14:14:41.440 INFO  [Logger,   29] - Connecting to tcp://10.65.53.50:40011... 
25.04.2018 14:14:41.518 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,   30] - Failed to obtain a distributed lock for actor system [klsrl]. Remaining retries: [1] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<>c__DisplayClass12_0.<GetNodesAsync>b__0(ServiceEntry x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Akka.Cluster.Discovery.DiscoveryService.<TryJoinAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<>c__DisplayClass16_1.<<-ctor>b__1>d.MoveNext()
25.04.2018 14:14:41.731 ERROR [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,   25] - Failed to obtain a distributed lock for actor system [klsrl] after 3 retries. Closing. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService.<>c__DisplayClass12_0.<GetNodesAsync>b__0(ServiceEntry x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Akka.Cluster.Discovery.DiscoveryService.<TryJoinAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Cluster.Discovery.LockingDiscoveryService.<TryJoinAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Cluster.Discovery.DiscoveryService.<>c__DisplayClass16_1.<<-ctor>b__1>d.MoveNext()
```

**Comment by vasily-kirichenko** [comment]
Solved: 
* I noticed that the Consul service named by the actor system is shown in the Consul Web UI, on a single instance. Stopping Consul on that server does not help - the service moved to "critical" status, but not disappear. 
* Starting Consul on that server solved the issue immediately.
