### ISSUE TITLE
Fails trying to parse valid Consul address

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#8]
Config (in CDATA in app.config)
```
cluster {
            discovery {
			  provider = akka.cluster.discovery.consul
			  consul {
				listener-url = "http://127.0.0.1:8500"
			  }
			}
		  }
```
Error
```
[ERROR][22.01.2018 8:44:30][Thread 0005][akka://klsrl/system/$a] Error while creating actor instance of type Akka.Cluster.Discovery.Consul.ConsulDiscoveryService with 1 args: (  listener-url : "http://127.0.0.1:8500"
)
Cause: [akka://klsrl/system/$a#1100608499]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Cluster.Discovery.Consul.ConsulDiscove
ryService with 1 args: (  listener-url : "http://127.0.0.1:8500"
) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Akka.Configuration.Hocon.HoconValue.ParsePositiveValue(String v)
   at Akka.Configuration.Hocon.HoconValue.GetTimeSpan(Boolean allowInfinite)
   at Akka.Configuration.Config.GetTimeSpan(String path, Nullable`1 default, Boolean allowInfinite)
   at Akka.Cluster.Discovery.Consul.ConsulSettings..ctor(Config config)
   at Akka.Cluster.Discovery.Consul.ConsulDiscoveryService..ctor(Config config)
```

**Comment by vasily-kirichenko** [comment]
Adding `class = "Akka.Cluster.Discovery.Consul.ConsulDiscoveryService, Akka.Cluster.Discovery.Consul"` solves the problem.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Horusiath/Akka.Cluster.Discovery/pull/9
